services:
  - type: web
    name: ai-learning-hub-backend
    env: node
    buildCommand: npm install
    startCommand: node simple-server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0